name: Deploy to AWS

on:
  push:
    branches:
      - main # Change if your branch is not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t nextjs-app .

      - name: Save Docker image to file
        run: docker save nextjs-app | gzip > nextjs-app.tar.gz

      - name: Upload Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: nextjs-app.tar.gz
          target: /home/${{ secrets.AWS_USER }}

      - name: SSH into EC2 and run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker load < nextjs-app.tar.gz
            docker run -d -p 3000:3000 --name nextjs-app nextjs-app
